version: "3.7"
services:
  ddmal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:8000"
    volumes:
      - "./drafts:/opt/drafts"
    command: bash -c "tail -f /dev/null"
  simssa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:8000"
    command: bash -c "tail -f /dev/null"
