version: "3.7"
services:
  ddmal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./drafts:/opt/drafts"
    command: bash -c "tail -f /dev/null"
  simssa:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "tail -f /dev/null"
